blank_issues_enabled: false
contact_links:
  - name: Support request
    url: https://s.gwdg.de/bxqZti
    about: For support requests, please have a look at our "Boost Union questions" thread in the "Themes" forum on moodle.org. Please do not generate a new issue for support questions here.