<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Theme Boost Union - Scheduled task for deleting stale optimized course card images.
 *
 * @package    theme_boost_union
 * @copyright  2024 Alexander Bias, lern.link GmbH <alexander.bias@lernlink.de>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace theme_boost_union\task;

/**
 * Remove stale optimized course card images.
 *
 * The optimized .webp thumbnails are generated by {@see \theme_boost_union\util\course::fetch_optimg()}
 * and stored in the "cardimg" file area under the system context. Their filenames encode the
 * content hash of the source image and the width they were rescaled to, in the form
 * "<contenthash>_<width>x.webp".
 *
 * A thumbnail becomes stale (and is deleted here) when either:
 *  - the configured width ("reducecoursecardimagesize") no longer matches the width in the
 *    filename, or
 *  - the course overview image it was generated from no longer exists.
 *
 * @package   theme_boost_union
 * @copyright  2024 Alexander Bias, lern.link GmbH <alexander.bias@lernlink.de>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class cleanup_cardimg extends \core\task\scheduled_task {

    /**
     * Return the name of the task shown in the admin UI.
     *
     * @return string
     */
    public function get_name() {
        return get_string('task_cleanup_cardimg', 'theme_boost_union');
    }

    /**
     * Delete optimized card images whose width setting changed or whose source image was removed.
     */
    public function execute() {
        global $DB;

        $fs = get_file_storage();
        $contextid = \context_system::instance()->id;

        // Current configured target width. When the feature is disabled (0 or empty) every
        // generated thumbnail is stale, so leave the setting as-is and let the width comparison
        // remove them all.
        $currentwidth = (int) get_config('theme_boost_union', 'reducecoursecardimagesize');

        $files = $fs->get_area_files($contextid, 'theme_boost_union', 'cardimg', 0, 'id', false);

        $deleted = 0;
        foreach ($files as $file) {
            $filename = $file->get_filename();

            // Parse "<contenthash>_<width>x.webp"; ignore anything that does not match.
            if (!preg_match('/^([0-9a-f]+)_(\d+)x\.webp$/', $filename, $matches)) {
                continue;
            }

            $sourcehash = $matches[1];
            $width = (int) $matches[2];

            $stale = false;

            // Stale if the width setting changed since this thumbnail was generated.
            if ($width !== $currentwidth) {
                $stale = true;

                // Stale if the course overview image it was based on no longer exists.
            } else if (!$DB->record_exists('files', [
                'contenthash' => $sourcehash,
                'component'   => 'course',
                'filearea'    => 'overviewfiles',
            ])) {
                $stale = true;
            }

            if ($stale) {
                $file->delete();
                $deleted++;
            }
        }

        mtrace("theme_boost_union: removed {$deleted} stale course card image(s).");
    }
}
